name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  GITHUB_PAGES_BUILD: True

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - uses: actions/checkout@v3
        with:
          lfs: true
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          checkout: false
